# Generated by Django 2.1.4 on 2019-01-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('bpub_date', models.DateTimeField(max_length=20)),
                ('bsell_date', models.DateField()),
            ],
        ),
    ]
